### ISSUE TITLE
Broken Stories dropdown

### ISSUE THREAD

**Issue by shteyn** [DigitalCareerInstitute/marketing-website#95] opened 2018-11-12 10:25 UTC
![signin template for bootstrap](https://user-images.githubusercontent.com/37113074/48341525-90cd5680-e66d-11e8-8a72-1cac1005872b.png)

**Comment by spielhoelle** [comment] 2018-11-12 11:05
Duplicate of #92

**Closed by spielhoelle** 2018-11-12 11:05 UTC
Labels: bug
