### ISSUE TITLE
Create responsive menu

### ISSUE THREAD

**Issue by spielhoelle** [DigitalCareerInstitute/marketing-website#109] opened 2018-11-14 20:05 UTC
It should be able toggle on and off - bootstrap like

**Comment by shteyn** [comment] 2018-11-22 12:58
Issue done by #133

**Comment by shteyn** [comment] 2018-11-28 08:46
The issue is appeared again after the last merge

**Comment by shteyn** [comment] 2018-11-28 09:15
issue closed by #145

**Closed by shteyn** 2018-11-28 09:15 UTC
Labels: BUG :beetle:, Done 👍, Frontend, Prio1 :fire:
